-- AlterTable
ALTER TABLE "provas" ADD COLUMN IF NOT EXISTS "inscricaoInicio" TIMESTAMP(3);
ALTER TABLE "provas" ADD COLUMN IF NOT EXISTS "inscricaoFim" TIMESTAMP(3);
ALTER TABLE "provas" ADD COLUMN IF NOT EXISTS "vagas" INTEGER;
ALTER TABLE "provas" ADD COLUMN IF NOT EXISTS "salario" TEXT;
ALTER TABLE "provas" ADD COLUMN IF NOT EXISTS "editalUrl" TEXT;
