/**
 * Prova real: CEBRASPE - PRF 2021 - Policial Rodoviario Federal (Edital PRF n.1/2021).
 * Gabarito conferido item a item contra o gabarito oficial preliminar publicado pela banca.
 */
import type { ExamLevel } from "../../src/generated/prisma";

const gabaritoRaw =
  "C C E C E C C E " +
  "C E C C E C E C C E E E C E E E C C E C " +
  "E E C C E E C C C E E C E E C E E C E C " +
  "E C C E C C E C C E C E E E C C C C E C " +
  "E E C C E C E E E C E E E C C C E E C E " +
  "C E E C E E C E C C E C E E E C E C E E " +
  "C E C C C C E E C E C C";
const gabarito = gabaritoRaw.split(" ").filter(Boolean);
if (gabarito.length !== 120) throw new Error(`esperado 120 itens no gabarito do PRF 2021, obtido ${gabarito.length}`);

function certoErrado(numero: number, enunciado: string, opts: { disciplina: string; assunto?: string; textoApoioChave?: string }) {
  const g = gabarito[numero - 1];
  return {
    numero,
    tipo: "CERTO_ERRADO" as const,
    enunciado,
    disciplina: opts.disciplina,
    assunto: opts.assunto,
    dificuldade: "MEDIUM" as const,
    gabarito: g,
    textoApoioChave: opts.textoApoioChave,
    alternativas: [
      { letra: "C", texto: "Certo", correta: g === "C" },
      { letra: "E", texto: "Errado", correta: g === "E" },
    ],
  };
}

export const prf2021Prova = {
  titulo: "PRF 2021 - Policial Rodoviario Federal",
  orgao: "Policia Rodoviaria Federal",
  banca: "CEBRASPE",
  cargo: "Policial Rodoviario Federal",
  ano: 2021,
  nivel: ["SUPERIOR"] satisfies ExamLevel[],
  duracaoMin: 300,
};

export const prf2021Textos = [
  {
    chave: "texto-ingles-texas",
    titulo: "Texto em ingles - crise energetica no Texas (CNN)",
    conteudo: `A deep freeze this week in the Lone Star state, which relies on electricity to heat many homes, is causing power demand to skyrocket. At the same time, natural gas, coal, wind and nuclear facilities in Texas have been knocked offline by the unthinkably low temperatures.
"The extreme cold is causing the entire system to freeze up," said Jason Bordoff, director of Columbia University's Center on Global Energy Policy. "All sources of energy are underperforming in the extreme cold because they're not designed to handle these unusual conditions."
The ripple effects are being felt around the nation as Texas' prolific oil-and-gas industry stumbles.
It's striking that these power outages are happening in a state with abundant energy resources. Texas produces more electricity than any other US state — generating almost twice as much as Florida, the next-closest, according to federal statistics.
Wind power is also booming in Texas, which produced about 28% of all the US wind-powered electricity in 2019, the EIA said. But the problem is that not only is Texas an energy superpower, it tends to be an above-average temperature state. That means its infrastructure is ill-prepared for the cold spell currently wreaking havoc. And the consequences are being felt by millions.
Critics of renewable energy have pointed out that wind turbines have frozen or needed to be shut down due to the extreme weather.
Even though other places with colder weather (like Iowa and Denmark) rely on wind for even larger shares of power, experts said the turbines in Texas were not winterized for the unexpected freeze.
But this is not just about wind turbines going down. Natural gas and coal-fired power plants need water to stay online. Yet those water facilities froze in the cold temperatures and others lost access to the electricity they require to operate.
It's too early to definitively say what went wrong in Texas and how to prevent similar outages. More information will need to be released by state authorities. Still, some experts say the criticism of wind power appears overdone already. "In terms of the blame game, the focus on wind is a red herring. It's more of a political issue than what is causing the power problems on the grid," said Dan Cohan, associate professor of environmental engineering at Rice University.
The energy crisis in Texas raises also questions about the nature of the state's deregulated and decentralized electric grid. Unlike other states, Texas has made a conscious decision to isolate its grid from the rest of the country.
That means that when things are running smoothly, Texas can't export excess power to neighboring states. And in the current crisis, it can't import power either.
Internet: <www.cnn.com> (adapted).`,
  },
  {
    chave: "texto-1a18-i",
    titulo: "Texto 1A18-I - historia da policia (C. Mauch)",
    conteudo: `Nos Estados Unidos da América, no século XIX, a passagem da polícia do sistema de justiça para o de governo da cidade significou também a passagem da noção de caça aos criminosos para a prevenção dos crimes, em um deslocamento do ato para o ator. Como na Europa, a ênfase na prevenção teria representado nova atitude diante do controle social, com o desenvolvimento pela polícia de uma habilidade específica, a de explicar e prevenir o comportamento criminoso. Isso acabou redundando no foco nas "classes perigosas", ou seja, em setores específicos da sociedade vistos como produtores de comportamento criminoso. Nesse processo, desenvolveram-se os vários campos de saber vinculados aos sistemas de justiça criminal, polícia e prisão, voltados para a identificação, para a explicação e para a prevenção do comportamento criminoso, agora visto como "desviante", como a medicina legal, a psiquiatria e, especialmente, a criminologia.
Na Europa ocidental, as novas instituições estatais de vigilância deveriam controlar o exercício da força em sociedades em que os níveis de violência física nas relações interpessoais e do Estado com a sociedade estavam em declínio. De acordo com a difundida teoria do processo civilizador, de Norbert Elias, no Ocidente moderno, a agressividade, assim como outras emoções e prazeres, foi domada, "refinada" e "civilizada". O autor estabelece um contraste entre a violência "franca e desinibida" do período medieval, que não excluía ninguém da vida social e era socialmente permitida e até certo ponto necessária, e o autocontrole e a moderação das emoções que acabaram por se impor na modernidade. A conversão do controle que se exercia por terceiros no autocontrole é relacionada à organização e à estabilização de Estados modernos, nos quais a monopolização da força física em órgãos centrais permitiu a criação de espaços pacificados. Em tais espaços, os indivíduos passaram a ser submetidos a regras e leis mais rigorosas, mas ficaram mais protegidos da irrupção da violência na sua vida, na medida em que as ameaças físicas tornaram-se despersonalizadas e monopolizadas por especialistas.
C. Mauch. Considerações sobre a história da polícia. In: MÉTIS: história & cultura, v. 6, n.º 11, jan./jun. 2007, p. 107-19 (com adaptações).`,
  },
];

export const prf2021Questoes = [
  certoErrado(1, "About ideas stated in the text above and the words used in it: Extremely cold temperatures in Texas created problems for the distribution of energy in the state.", { disciplina: "Ingles", assunto: "Reading comprehension", textoApoioChave: "texto-ingles-texas" }),
  certoErrado(2, "In the last paragraph of the text, \"That\" refers to the decision by Texas to isolate its energy grid from the rest of the country.", { disciplina: "Ingles", assunto: "Reading comprehension", textoApoioChave: "texto-ingles-texas" }),
  certoErrado(3, "Despite the cold temperatures, energy production in Texas continued unimpeded.", { disciplina: "Ingles", assunto: "Reading comprehension", textoApoioChave: "texto-ingles-texas" }),
  certoErrado(4, "Changes in energy production in Texas are having an impact across the United States.", { disciplina: "Ingles", assunto: "Reading comprehension", textoApoioChave: "texto-ingles-texas" }),
  certoErrado(5, "There are other states, like Florida, that produce energy on a level similar to that of Texas.", { disciplina: "Ingles", assunto: "Reading comprehension", textoApoioChave: "texto-ingles-texas" }),
  certoErrado(6, "There are places in the world where wind power works well in freezing temperatures.", { disciplina: "Ingles", assunto: "Reading comprehension", textoApoioChave: "texto-ingles-texas" }),
  certoErrado(7, "In \"Natural gas and coal-fired power plants need water to stay online. Yet those water facilities froze in the cold temperatures and others lost access to the electricity they require to operate\", it is possible to substitute \"Yet\" for Even so without changing the meaning of the sentence.", { disciplina: "Ingles", assunto: "Vocabulario e coesao", textoApoioChave: "texto-ingles-texas" }),
  certoErrado(8, "The text points to the lack of wind as the primary cause for a dip in the production of wind energy during the period described.", { disciplina: "Ingles", assunto: "Reading comprehension", textoApoioChave: "texto-ingles-texas" }),
  certoErrado(9, "A transferência da polícia do sistema de justiça para o governo da cidade marca o que pode ser considerado uma mudança de paradigma no que se refere ao papel da polícia na sociedade.", { disciplina: "Portugues", assunto: "Interpretacao de texto", textoApoioChave: "texto-1a18-i" }),
  certoErrado(10, "Seriam mantidos a correção gramatical e os sentidos do texto caso o segundo período do primeiro parágrafo fosse reescrito da seguinte maneira: Porque nos países europeus houve empenho em prevenir crimes, o que representou nova atitude de controle social, o resultado foi o desenvolvimento de uma habilidade específica pelas autoridades policiais: a de explicar e prevenir o crime.", { disciplina: "Portugues", assunto: "Reescrita e correcao gramatical", textoApoioChave: "texto-1a18-i" }),
  certoErrado(11, "Infere-se da leitura do primeiro parágrafo do texto que o desenvolvimento de áreas científicas ligadas à justiça criminal no século XIX está associado a visões preconceituosas sobre certos grupos de indivíduos.", { disciplina: "Portugues", assunto: "Interpretacao de texto", textoApoioChave: "texto-1a18-i" }),
  certoErrado(12, "Depreende-se do segundo parágrafo do texto que a violência na era medieval era comum e socialmente aceita.", { disciplina: "Portugues", assunto: "Interpretacao de texto", textoApoioChave: "texto-1a18-i" }),
  certoErrado(13, "Conclui-se do texto que o monopólio da violência legítima pelo Estado deveu-se à necessidade de reação aos índices insustentáveis de violência física entre os indivíduos.", { disciplina: "Portugues", assunto: "Interpretacao de texto", textoApoioChave: "texto-1a18-i" }),
  certoErrado(14, "Um dos traços característicos da modernidade, segundo Norbert Elias, é a renúncia de certas emoções e de certos prazeres pelos indivíduos, que, em compensação, passaram a ser protegidos da violência devido à atuação do Estado.", { disciplina: "Portugues", assunto: "Interpretacao de texto", textoApoioChave: "texto-1a18-i" }),
  certoErrado(15, "O pronome \"Isso\", que introduz o terceiro período do primeiro parágrafo do texto, poderia ser corretamente substituído por O que.", { disciplina: "Portugues", assunto: "Coesao textual", textoApoioChave: "texto-1a18-i" }),
  certoErrado(16, "Infere-se do segundo parágrafo do texto que a agressividade humana passou por um processo de transformação gradativo de perda de aspectos primitivos e animalescos.", { disciplina: "Portugues", assunto: "Interpretacao de texto", textoApoioChave: "texto-1a18-i" }),
  certoErrado(17, "O emprego do vocábulo \"irrupção\", no último período do texto, indica que a violência atingia os indivíduos de forma súbita.", { disciplina: "Portugues", assunto: "Semantica e vocabulario", textoApoioChave: "texto-1a18-i" }),
  certoErrado(18, "Mantém-se a correção gramatical do trecho \"o autocontrole e a moderação das emoções que acabaram por se impor na modernidade\", do texto, caso a forma verbal \"impor\" seja flexionada no plural imporem.", { disciplina: "Portugues", assunto: "Concordancia verbal", textoApoioChave: "texto-1a18-i" }),
  certoErrado(19, "O trecho \"A conversão do controle que se exercia por terceiros no autocontrole é relacionada à organização e à estabilização de Estados modernos\" poderia ser reescrito da seguinte forma, sem prejuízo para os sentidos e para a correção gramatical do texto: Converter o controle efetuado por terceiros a autocontrole concatena a organização e estabilização dos Estados do mundo moderno.", { disciplina: "Portugues", assunto: "Reescrita e correcao gramatical", textoApoioChave: "texto-1a18-i" }),
  certoErrado(20, "A coerência e os sentidos do texto seriam mantidos caso fosse suprimido o artigo \"os\", no trecho \"desenvolveram-se os vários campos de saber\", no último período do primeiro parágrafo.", { disciplina: "Portugues", assunto: "Coesao e coerencia", textoApoioChave: "texto-1a18-i" }),
  certoErrado(21, "A correção gramatical do último período do texto seria mantida, embora seu sentido original fosse prejudicado, se a locução \"na medida em que\" fosse substituída por à medida que e a vírgula empregada logo após \"vida\" fosse suprimida.", { disciplina: "Portugues", assunto: "Reescrita e correcao gramatical", textoApoioChave: "texto-1a18-i" }),
  certoErrado(22, "Considerando as disposições do Manual de Redação da Presidência da República (MRPR) acerca da redação oficial: entre as características da redação oficial incluem-se a objetividade, a impessoalidade e a informatividade.", { disciplina: "Portugues", assunto: "Redacao oficial" }),
  certoErrado(23, "Considerando as disposições do Manual de Redação da Presidência da República (MRPR) acerca da redação oficial: de acordo com a legislação vigente, o e-mail institucional tem valor documental e, por isso, deve ser aceito como documento original.", { disciplina: "Portugues", assunto: "Redacao oficial" }),
  certoErrado(24, "Considerando as disposições do Manual de Redação da Presidência da República (MRPR) acerca da redação oficial: na identificação do signatário de uma comunicação oficial destinada a uma pessoa do sexo feminino, dispensa-se flexão de gênero no nome do cargo.", { disciplina: "Portugues", assunto: "Redacao oficial" }),
  certoErrado(25, "Considerando as disposições do Manual de Redação da Presidência da República (MRPR) acerca da redação oficial: o vocativo, nas comunicações oficiais, deverá ser sempre seguido de vírgula.", { disciplina: "Portugues", assunto: "Redacao oficial" }),
  certoErrado(26, "Considerando as disposições do Manual de Redação da Presidência da República (MRPR) acerca da redação oficial: o assunto das comunicações oficiais deve apresentar de forma geral o que será tratado no documento e seu formato deve seguir as orientações do MRPR, conforme o exemplo a seguir: Assunto: Realização de concurso público.", { disciplina: "Portugues", assunto: "Redacao oficial" }),
  certoErrado(27, "Foi modelado que o espalhamento de uma notícia em uma população — entendido como o percentual de indivíduos dessa população que recebe essa notícia por unidade de tempo — é diretamente proporcional ao percentual de indivíduos da população que já conhecem a notícia multiplicado pelo percentual de indivíduos dessa população que ainda não a conhecem até aquele instante. A constante k de proporcionalidade depende, entre outros fatores, do impacto da notícia na vida dos envolvidos e de propriedades dos meios de comunicação disponíveis. Considerando k = 1: de acordo com a modelagem realizada, é possível que, em determinado instante, o espalhamento da notícia seja superior a 50% por unidade de tempo.", { disciplina: "Raciocinio Logico-Matematico", assunto: "Modelagem e proporcionalidade" }),
  certoErrado(28, "Na mesma modelagem (espalhamento de notícia diretamente proporcional ao produto do percentual de quem já conhece pelo percentual de quem não conhece, com k = 1): se, em determinado instante, 30% da população já conhece a notícia, então, nesse instante, o seu espalhamento estaria em patamar superior a 20% por unidade de tempo.", { disciplina: "Raciocinio Logico-Matematico", assunto: "Modelagem e proporcionalidade" }),
  certoErrado(29, "Na mesma modelagem do espalhamento de notícia: o espalhamento de uma notícia será tanto maior quanto maior for o número de pessoas que dela tiverem tomado conhecimento.", { disciplina: "Raciocinio Logico-Matematico", assunto: "Modelagem e proporcionalidade" }),
  certoErrado(30, "Na mesma modelagem do espalhamento de notícia: se, em determinado instante, o espalhamento de uma notícia é igual a 16% por unidade de tempo, então, nesse instante, mais de 75% da população ainda desconhece a notícia.", { disciplina: "Raciocinio Logico-Matematico", assunto: "Modelagem e proporcionalidade" }),
  certoErrado(31, "Em uma operação da PRF, foram fiscalizados: 20 veículos automotores até o fim da primeira hora; 60 até o fim da segunda hora; 120 até o fim da terceira hora; 200 até o fim da quarta hora; e 300 até o fim da quinta hora. O padrão numérico observado manteve-se até o fim da décima hora, quando foi finalizada a operação. Mais de 550 veículos terão sido fiscalizados até o fim da sétima hora de realização da operação.", { disciplina: "Raciocinio Logico-Matematico", assunto: "Sequencias numericas" }),
  certoErrado(32, "Na mesma situação hipotética da operação de fiscalização de veículos: considere que {qn}, para n variando de 1 a 10, seja a sequência numérica formada pelas quantidades de veículos fiscalizados apenas no decorrer da n-ésima hora de realização da operação (q1 é a quantidade fiscalizada apenas na primeira hora, q2 apenas na segunda hora, e assim por diante). Nessa situação, a sequência {qn}, para n variando de 1 a 10, é uma progressão aritmética.", { disciplina: "Raciocinio Logico-Matematico", assunto: "Progressao aritmetica" }),
  certoErrado(33, "No que se refere a Internet, intranet e noções do sistema operacional Windows: no Windows, ainda que seja possível compartilhar configurações — como plano de fundo e histórico de navegação do Internet Explorer — entre computadores que utilizem a mesma conta em outras máquinas com Windows 10, não é permitido, em razão da segurança, o compartilhamento de senhas.", { disciplina: "Informatica", assunto: "Windows 10" }),
  certoErrado(34, "No que se refere a Internet, intranet e Windows: embora as versões mais atuais do Mozilla Firefox e do Google Chrome permitam salvar e sincronizar senhas para realizar, posteriormente, login automático em formulários de sítios da Internet, essa ação somente será possível se os sítios em questão estiverem disponibilizados em uma intranet e utilizarem o protocolo HTTPS.", { disciplina: "Informatica", assunto: "Navegadores" }),
  certoErrado(35, "No que se refere a Internet, intranet e Windows: caso sejam digitados os termos descritos a seguir na ferramenta de busca do Google, serão pesquisadas publicações que contenham os termos \"PRF\" e \"campanha\" na rede social Twitter: campanha PRF @twitter", { disciplina: "Informatica", assunto: "Ferramentas de busca" }),
  certoErrado(36, "Com referência à transformação digital: a Internet das coisas (IoT) aumenta a quantidade e a complexidade dos dados por meio de novas formas e novas fontes de informações, influenciando diretamente em uma ou mais das características do big data, a exemplo de volume, velocidade e variedade.", { disciplina: "Informatica", assunto: "Transformacao digital e big data" }),
  certoErrado(37, "A respeito de segurança e de cloud computing: o firewall da próxima geração (NGFW) dispõe, em um mesmo equipamento, de recursos como IDS (intrusion detection system), IPS (intrusion prevention system) e antivírus.", { disciplina: "Informatica", assunto: "Seguranca da informacao" }),
  certoErrado(38, "A respeito de segurança e de cloud computing: identifica-se Software como Serviço (SaaS) quando um provedor de serviços oferece acesso a um ambiente baseado em cloud, no qual os usuários podem construir e disponibilizar aplicativos.", { disciplina: "Informatica", assunto: "Cloud computing" }),
  certoErrado(39, "A respeito de segurança e de cloud computing: ransomware é um programa malicioso de computador que se propaga por meio da inserção de cópias de si mesmo em arquivos criptografados.", { disciplina: "Informatica", assunto: "Malware" }),
  certoErrado(40, "Um projétil foi lançado obliquamente em relação ao solo em um local onde a aceleração da gravidade é constante e a resistência do ar é desprezível. Durante todo o movimento, a aceleração vetorial do projétil será constante.", { disciplina: "Fisica", assunto: "Lancamento obliquo" }),
  certoErrado(41, "No mesmo lançamento oblíquo (gravidade constante, sem resistência do ar): na posição de altura máxima, a força resultante sobre o projétil será nula.", { disciplina: "Fisica", assunto: "Lancamento obliquo" }),
  certoErrado(42, "No mesmo lançamento oblíquo: na posição de altura máxima, a velocidade vetorial do projétil será nula.", { disciplina: "Fisica", assunto: "Lancamento obliquo" }),
  certoErrado(43, "Um projétil, de massa m e velocidade v, colidiu frontalmente com um bloco de madeira de massa M que estava em repouso em uma superfície horizontal sem atrito, preso a uma mola ideal de constante elástica k. Após a colisão, o projétil e o bloco desenvolveram um movimento solidário, o que provocou, na mola, uma compressão máxima igual a x. Na posição de compressão máxima, a energia potencial elástica armazenada na mola tem valor menor que o da energia cinética do projétil antes da colisão.", { disciplina: "Fisica", assunto: "Colisoes e energia mecanica" }),
  certoErrado(44, "Na mesma situação da colisão projétil-bloco-mola: como não há atrito entre o bloco de madeira e a mesa horizontal, a conservação da energia mecânica garante que o valor da energia cinética do sistema imediatamente antes da colisão seja igual ao valor da energia cinética do sistema imediatamente após a colisão.", { disciplina: "Fisica", assunto: "Colisoes e energia mecanica" }),
  certoErrado(45, "A respeito da ética no serviço público, da administração pública federal bem como dos servidores públicos federais e seus direitos e deveres: a revelação de segredo do qual o servidor se apropriou em razão do cargo enseja a penalidade de demissão, o que implica o ressarcimento ao erário por parte do servidor.", { disciplina: "Etica no Servico Publico", assunto: "Regime disciplinar" }),
  certoErrado(46, "A respeito da ética no serviço público e dos servidores públicos federais: o diretor-geral da Polícia Rodoviária Federal, desde que satisfeitos os requisitos legais, poderá realizar a contratação direta de empresa na qual um primo seja sócio.", { disciplina: "Etica no Servico Publico", assunto: "Nepotismo e contratacao" }),
  certoErrado(47, "A respeito da ética no serviço público: de acordo com o Código de Ética Profissional do Servidor Público Civil do Poder Executivo Federal, ausência de servidor do seu local de trabalho é fator de desmoralização do serviço público, já que pode acarretar desordem nas relações humanas.", { disciplina: "Etica no Servico Publico", assunto: "Codigo de Etica Profissional" }),
  certoErrado(48, "A respeito da ética no serviço público: a estratégia, que consiste em um mecanismo para o exercício da governança pública, compreende a definição de diretrizes, objetivos, planos e ações, para que os serviços de responsabilidade da organização alcancem o resultado pretendido.", { disciplina: "Etica no Servico Publico", assunto: "Governanca publica" }),
  certoErrado(49, "A respeito da ética no serviço público: caso terceiro solicite, por telefone, informação sobre aquisições de determinado órgão público, o servidor deverá orientá-lo a preencher o formulário padrão, disponibilizado em meio eletrônico e físico, com os dados exigidos pela lei.", { disciplina: "Etica no Servico Publico", assunto: "Acesso a informacao" }),
  certoErrado(50, "A respeito da ética no serviço público: o investigado poderá ter vista dos autos, com direito a cópia se assim o desejar, mesmo antes da notificação da existência de procedimento investigatório em comissão de ética.", { disciplina: "Etica no Servico Publico", assunto: "Processo etico-disciplinar" }),
  certoErrado(51, "No que se refere à rede de transportes no Brasil: a duplicação dos principais eixos rodoviários, a restruturação do modelo de investimento e de exploração das ferrovias e a expansão e o aumento da capacidade da malha ferroviária são considerados condições para o desenvolvimento das regiões brasileiras no que diz respeito às redes de transporte.", { disciplina: "Geografia", assunto: "Redes de transporte no Brasil" }),
  certoErrado(52, "No que se refere à rede de transportes no Brasil: na escala interurbana, o Brasil apresenta uma rede de transportes integrada, diversa e eficiente, o que resulta em integração regional e competitividade no contexto da economia nacional.", { disciplina: "Geografia", assunto: "Redes de transporte no Brasil" }),
  certoErrado(53, "No que se refere à rede de transportes no Brasil: as políticas públicas no Brasil, sobretudo as implementadas a partir da segunda metade do século passado, incentivaram o transporte rodoviário de pessoas e de cargas em detrimento de outros modais de transporte.", { disciplina: "Geografia", assunto: "Redes de transporte no Brasil" }),
  certoErrado(54, "Com relação à estrutura urbana brasileira e às grandes metrópoles: as metrópoles brasileiras são arranjos populacionais acima de um milhão de habitantes que exercem influência direta sobre os demais níveis de cidades na rede urbana.", { disciplina: "Geografia", assunto: "Estrutura urbana brasileira" }),
  certoErrado(55, "Com relação à estrutura urbana brasileira: os arranjos populacionais de Campinas e Ribeirão Preto, no estado de São Paulo, e de Uberlândia, em Minas Gerais, configuram-se como metrópoles em ascensão na rede urbana brasileira e encontram-se no primeiro nível da hierarquia urbana.", { disciplina: "Geografia", assunto: "Estrutura urbana brasileira" }),
  certoErrado(56, "No que se refere à legislação de trânsito brasileira: em rodovias de via dupla de zonas rurais em que não houver sinalização regulamentadora, deve-se aplicar a automóveis, camionetas e motocicletas o mesmo limite máximo de velocidade permitido para transitar.", { disciplina: "Legislacao de Transito", assunto: "Codigo de Transito Brasileiro" }),
  certoErrado(57, "No que se refere à legislação de trânsito brasileira: veículos em movimento em via pública que possuam espelhos retrovisores em ambos os lados poderão usar cortinas nas áreas envidraçadas.", { disciplina: "Legislacao de Transito", assunto: "Codigo de Transito Brasileiro" }),
  certoErrado(58, "No que se refere à legislação de trânsito brasileira: para que autoridade ou agente policial possa autorizar a remoção de veículos envolvidos em acidente de trânsito ocorrido em leito de via pública que tenha causado lesão em pessoas e dano aos veículos envolvidos, é necessário que antes tenha sido prestado socorro às vítimas e realizada a perícia no local.", { disciplina: "Legislacao de Transito", assunto: "Codigo de Transito Brasileiro" }),
  certoErrado(59, "No que se refere à legislação de trânsito brasileira: cidadão que seja penalmente inimputável não pode obter habilitação para conduzir veículo automotor e elétrico.", { disciplina: "Legislacao de Transito", assunto: "Codigo de Transito Brasileiro" }),
  certoErrado(60, "No que se refere à legislação de trânsito brasileira: considere que, em determinada rodovia federal, tenha havido um acidente, sem vítimas, em que um veículo colidira com outro, do que resultara, para os dois veículos, em avaria e em dano patrimonial. Nessa situação hipotética, o causador do acidente deverá preservar o local, a fim de facilitar os trabalhos da polícia e da perícia, sob pena de responder por grave infração administrativa de trânsito.", { disciplina: "Legislacao de Transito", assunto: "Codigo de Transito Brasileiro" }),
  certoErrado(61, "Considerando as resoluções do Conselho Nacional de Trânsito (CONTRAN) e suas alterações: a fiscalização de trânsito por videomonitoramento independe de sinalização na via e, em caso de infração, a autoridade ou o agente de trânsito responsável pela lavratura de auto de infração deve indicar, no campo observação, informações relativas ao modo de constatação da referida infração.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(62, "Considerando as resoluções do CONTRAN: a emissão de Certificado de Registro e Licenciamento de Veículo em meio digital (CRLV-e), no qual constam o Certificado de Registro de Veículo (CRV) e o Certificado de Licenciamento Anual (CLA), é obrigatória se houver transferência de propriedade, sendo dispensável em caso de mudança de município de residência do proprietário.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(63, "Considerando as resoluções do CONTRAN: os objetivos da campanha educativa de trânsito do ano de 2021 incluem divulgar, mensalmente, temas com orientações específicas, as quais promovam, por exemplo, reflexões sobre como lesões e sequelas psicológicas e sociais decorrentes de acidentes de trânsito impactam a vida das vítimas e de seus familiares.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(64, "Considerando as resoluções do CONTRAN: para a medição de velocidade de veículos automotores elétricos, reboques e semirreboques em rodovias, utilizam-se medidores de velocidade do tipo fixo; entre estes, somente o medidor de velocidade do tipo fixo redutor deve obrigatoriamente ser dotado de display.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(65, "Considerando as resoluções do CONTRAN: como os reboques e os semirreboques são identificados somente por placa de identificação veicular (PIV) traseira, caso seja necessário, veículos equipados com engates para reboques ou com carroceria intercambiável deverão obrigatoriamente usar uma segunda PIV traseira.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(66, "Ainda com relação às resoluções do CONTRAN e suas alterações: lanternas especiais de emergência que emitem luz de cor azul são de uso exclusivo de veículos que estejam devidamente identificados e destinados a socorro de incêndio e salvamento, a exemplo dos veículos de polícia, de fiscalização e de operações de trânsito e de ambulâncias, quando da efetiva prestação do serviço de urgência.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(67, "Ainda com relação às resoluções do CONTRAN: infração de trânsito concomitante é aquela em que o cometimento de uma infração tem como pressuposto o cometimento de outra.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(68, "Ainda com relação às resoluções do CONTRAN: o Plano Nacional de Trânsito é composto por um rol de iniciativas e de ações, sendo um de seus pilares a mobilidade e a engenharia.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(69, "Ainda com relação às resoluções do CONTRAN: a circulação de veículos em via pode ocorrer a título precário, sendo vedado o transporte de passageiro que esteja em pé no veículo ou que tenha menos de dezoito anos de idade no caso de transporte de passageiros em veículos de carga ou misto.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(70, "Ainda com relação às resoluções do CONTRAN: é permitido que veículos de passageiros, ônibus, micro-ônibus e caminhões transitem em rodovia com trincas em seus para-brisas, desde que elas estejam dentro do limite previsto em norma específica e não haja fratura de configuração circular.", { disciplina: "Legislacao de Transito", assunto: "Resolucoes CONTRAN" }),
  certoErrado(71, "Acerca do registrador instantâneo e inalterável de velocidade e tempo: o equipamento em questão deve apresentar o tempo de movimentação do veículo, bem como suas interrupções.", { disciplina: "Legislacao de Transito", assunto: "Registrador de velocidade e tempo" }),
  certoErrado(72, "Acerca do registrador instantâneo e inalterável de velocidade e tempo: em caso de operação de fiscalização do registrador, o policial rodoviário federal deve identificar-se e assinar o verso do disco ou da fita diagrama, além de mencionar o local, a data e horário em que ocorreu a fiscalização.", { disciplina: "Legislacao de Transito", assunto: "Registrador de velocidade e tempo" }),
  certoErrado(73, "Acerca do registrador instantâneo e inalterável de velocidade e tempo: é de seis meses o prazo em que as informações relativas às últimas vinte e quatro horas de operação do veículo devem ficar à disposição das autoridades competentes em caso de acidente.", { disciplina: "Legislacao de Transito", assunto: "Registrador de velocidade e tempo" }),
  certoErrado(74, "Com relação a limites de peso e dimensões para a circulação de veículos em vias públicas, excetuadas as condições para a emissão das autorizações especiais de trânsito: o comprimento máximo permitido para a circulação de veículos não articulados em vias públicas é de 14,00 metros.", { disciplina: "Legislacao de Transito", assunto: "Peso e dimensoes de veiculos" }),
  certoErrado(75, "Com relação a limites de peso e dimensões: cumpridos os requisitos legais, para a combinação de veículos de carga com mais de duas unidades, incluída a unidade tratora, o peso bruto total deve ser de até 60 toneladas.", { disciplina: "Legislacao de Transito", assunto: "Peso e dimensoes de veiculos" }),
  certoErrado(76, "Com relação a limites de peso e dimensões: a largura máxima autorizada para a circulação de veículos em via pública, com ou sem carga, é de 2,50 metros.", { disciplina: "Legislacao de Transito", assunto: "Peso e dimensoes de veiculos" }),
  certoErrado(77, "No que se refere à fiscalização do tempo de direção e de descanso do motorista profissional: na condução de veículo de carga com peso bruto total superior a 4.536 kg, é permitido ao motorista profissional dirigir por até seis horas e meia ininterruptas.", { disciplina: "Legislacao de Transito", assunto: "Tempo de direcao e descanso" }),
  certoErrado(78, "No que se refere à fiscalização do tempo de direção e de descanso do motorista profissional: a fiscalização do tempo de direção e do intervalo de descanso pode ocorrer por meio da verificação do diário de bordo, da papeleta ou da ficha de trabalho externo, fornecidos pelo empregador.", { disciplina: "Legislacao de Transito", assunto: "Tempo de direcao e descanso" }),
  certoErrado(79, "No que se refere à fiscalização do tempo de direção e de descanso do motorista profissional: a responsabilidade pela guarda, pela proteção e pela precisão das informações contidas no equipamento registrador instantâneo inalterável de velocidade e de tempo é do proprietário do veículo.", { disciplina: "Legislacao de Transito", assunto: "Tempo de direcao e descanso" }),
  certoErrado(80, "No que concerne a campanha educativa de trânsito e fiscalização de peso dos veículos por balança rodoviária: em rodovias federais, na fiscalização de peso dos veículos por balança rodoviária, é admitida a tolerância de 12,5% sobre os limites de peso regulamentares por eixo de veículos transmitidos à superfície das vias públicas.", { disciplina: "Legislacao de Transito", assunto: "Fiscalizacao de peso" }),
  certoErrado(81, "No que concerne a campanha educativa de trânsito e fiscalização de peso: excetuados os produtos perigosos e a critério do policial rodoviário federal, desde que observadas as condições de segurança, produtos perecíveis e cargas vivas podem ser dispensados do remanejamento ou transbordo em caso de excesso de peso veicular.", { disciplina: "Legislacao de Transito", assunto: "Fiscalizacao de peso" }),
  certoErrado(82, "No que concerne a campanha educativa de trânsito: o slogan da campanha educativa de trânsito de 2021, a qual deve ser veiculada, obrigatoriamente, nos meios de comunicação social, em toda peça publicitária de produtos automobilísticos, é: \"No trânsito, sua responsabilidade salva vidas\".", { disciplina: "Legislacao de Transito", assunto: "Campanha educativa de transito" }),
  certoErrado(83, "Acerca dos requisitos mínimos de segurança para o transporte de cargas em veículos: para a amarração de carga, é proibida a utilização de cordas, sendo permitido o seu uso exclusivamente para a fixação da lona de cobertura, quando necessário.", { disciplina: "Legislacao de Transito", assunto: "Transporte de cargas" }),
  certoErrado(84, "Acerca dos requisitos mínimos de segurança para o transporte de cargas em veículos: quando não há pontos de amarração adequados ou em número suficiente, pode-se realizar a fixação dos dispositivos de amarração no próprio chassi do veículo.", { disciplina: "Legislacao de Transito", assunto: "Transporte de cargas" }),
  certoErrado(85, "Acerca dos requisitos mínimos de segurança para o transporte de cargas em veículos: para a amarração da carga, devem ser utilizadas cintas têxteis, correntes ou cabos de aço, com resistência total à ruptura por tração de, no mínimo, 1,50 vez o peso da carga.", { disciplina: "Legislacao de Transito", assunto: "Transporte de cargas" }),
  certoErrado(86, "Determinado órgão público firmou contrato administrativo com uma empresa de reconhecida especialização no mercado, para a prestação de serviços de treinamento de pessoal de natureza singular aos seus servidores. Durante a execução do contrato, a empresa descumpriu uma das cláusulas contratuais. A administração pública, então, aplicou multa por inexecução parcial do acordado. Insatisfeita, a empresa impetrou mandado de segurança no Poder Judiciário em face do ato administrativo que aplicara a penalidade sem prévia oitiva. A impetração de mandado de segurança configura controle judicial de mérito administrativo.", { disciplina: "Direito Administrativo", assunto: "Controle da administracao publica" }),
  certoErrado(87, "Na mesma situação hipotética do contrato administrativo: o ajuizamento da ação judicial para conter eventuais abusos praticados pela administração pública caracteriza a aplicação do princípio da sindicabilidade.", { disciplina: "Direito Administrativo", assunto: "Controle da administracao publica" }),
  certoErrado(88, "Na mesma situação hipotética: órgão público é ente descentralizado da administração indireta que possui personalidade jurídica de direito público.", { disciplina: "Direito Administrativo", assunto: "Organizacao administrativa" }),
  certoErrado(89, "Na mesma situação hipotética: a aplicação da multa em questão decorre do poder administrativo disciplinar.", { disciplina: "Direito Administrativo", assunto: "Poderes administrativos" }),
  certoErrado(90, "Na mesma situação hipotética: essa situação caracteriza contratação direta por dispensa de licitação.", { disciplina: "Direito Administrativo", assunto: "Licitacoes e contratos" }),
  certoErrado(91, "Acerca da carreira de policial rodoviário federal: a promoção do policial rodoviário federal para a segunda classe depende de participação em cursos de capacitação cujo conteúdo seja compatível com as atribuições do cargo e que tenha duração de, no mínimo, 150 horas.", { disciplina: "Direito Administrativo", assunto: "Carreira de PRF" }),
  certoErrado(92, "Acerca da carreira de policial rodoviário federal: as atribuições do policial rodoviário federal de terceira classe, cuja jornada de trabalho é de quarenta horas semanais, incluem realizar patrulhamento e policiamento ostensivo.", { disciplina: "Direito Administrativo", assunto: "Carreira de PRF" }),
  certoErrado(93, "Acerca de direitos fundamentais, garantias e remédios constitucionais: a manifestação pública em defesa da abolição de crime, por ser considerada incitação à prática de fato criminoso, não está protegida pela liberdade de reunião.", { disciplina: "Direito Constitucional", assunto: "Direitos fundamentais" }),
  certoErrado(94, "Acerca de direitos fundamentais, garantias e remédios constitucionais: autoriza-se o confisco de bem utilizado para o tráfico de drogas nas situações em que se constatar que houve habitualidade do uso do bem para a prática do referido crime.", { disciplina: "Direito Constitucional", assunto: "Direitos fundamentais" }),
  certoErrado(95, "Acerca de direitos fundamentais, garantias e remédios constitucionais: as hipóteses de perda da nacionalidade brasileira previstas na Constituição Federal de 1988 têm natureza taxativa, de modo que nem mesmo convenções ou tratados internacionais podem ampliá-las.", { disciplina: "Direito Constitucional", assunto: "Nacionalidade" }),
  certoErrado(96, "Acerca de direitos fundamentais, garantias e remédios constitucionais: a Constituição Federal de 1988 não garante o direito à escusa de consciência sobre o dever de votar para os maiores de 18 anos de idade e para os menores de 70 anos de idade.", { disciplina: "Direito Constitucional", assunto: "Direitos politicos" }),
  certoErrado(97, "Acerca de direitos fundamentais, garantias e remédios constitucionais: de acordo com o Supremo Tribunal Federal, não é cabível habeas data para a obtenção de informações a respeito da identidade de responsáveis por agressões e denúncias feitas contra o impetrante.", { disciplina: "Direito Constitucional", assunto: "Remedios constitucionais" }),
  certoErrado(98, "A respeito do regime constitucional da defesa do Estado e das instituições democráticas: durante a vigência do estado de sítio, as imunidades parlamentares poderão ser suspensas pelo voto de dois terços dos membros da respectiva casa legislativa.", { disciplina: "Direito Constitucional", assunto: "Defesa do Estado" }),
  certoErrado(99, "A respeito do regime constitucional da defesa do Estado: em caso de decretação do estado de sítio em razão de comoção interna autorizada pelo Congresso Nacional, admite-se a suspensão de todas as garantias constitucionais.", { disciplina: "Direito Constitucional", assunto: "Defesa do Estado" }),
  certoErrado(100, "Em uma abordagem durante blitz de rotina em rodovia federal, o policial constatou alteração no chassi do veículo que estava sendo fiscalizado. Questionado pelo policial, o condutor ofereceu-lhe grande quantia em dinheiro para que fosse liberado de imediato. A adulteração grosseira do chassi do veículo não caracteriza crime impossível.", { disciplina: "Direito Penal", assunto: "Crime impossivel e falsificacao" }),
  certoErrado(101, "Na mesma situação hipotética da adulteração de chassi: a remarcação de novo número no chassi e a falsificação do certificado de registro do veículo caracterizam crime único de falsificação de documento público.", { disciplina: "Direito Penal", assunto: "Falsificacao de documento" }),
  certoErrado(102, "Na mesma situação hipotética: a remarcação do chassi com o mesmo número original do veículo caracteriza crime contra a fé pública e infração administrativa de trânsito.", { disciplina: "Direito Penal", assunto: "Falsificacao de documento" }),
  certoErrado(103, "Na mesma situação hipotética: se o policial não aceitar o dinheiro oferecido, a conduta da pessoa deve ser punida na modalidade tentada.", { disciplina: "Direito Penal", assunto: "Corrupcao ativa" }),
  certoErrado(104, "Na mesma situação hipotética: ao oferecer dinheiro para ser irregularmente liberado da blitz, o condutor praticou o crime de corrupção ativa.", { disciplina: "Direito Penal", assunto: "Corrupcao ativa" }),
  certoErrado(105, "Durante uma abordagem em via pública, tendo suspeitado do comportamento de determinado condutor e constatado rasura na carteira nacional de habilitação (CNH) por ele apresentada, o policial rodoviário, após efetuar busca no veículo e apreender mercadoria proibida, deu-lhe voz de prisão, em razão da prática de crime de ação penal pública. A busca e a apreensão no veículo foram ilícitas, já que o policial as realizou sem autorização judicial.", { disciplina: "Direito Processual Penal", assunto: "Busca e apreensao" }),
  certoErrado(106, "Na mesma situação hipotética da abordagem com CNH rasurada: a situação caracteriza flagrante próprio e, em até vinte e quatro horas após a realização da prisão, deverá ser entregue a nota de culpa ao preso.", { disciplina: "Direito Processual Penal", assunto: "Prisao em flagrante" }),
  certoErrado(107, "Na mesma situação hipotética: a identificação criminal do condutor não poderá ser feita, uma vez que ele foi identificado civilmente pela CNH.", { disciplina: "Direito Processual Penal", assunto: "Identificacao criminal" }),
  certoErrado(108, "Na mesma situação hipotética: o policial poderá ser arrolado como testemunha, caso em que seu depoimento terá valor probatório superior ao do interrogatório do condutor.", { disciplina: "Direito Processual Penal", assunto: "Prova testemunhal" }),
  certoErrado(109, "Na mesma situação hipotética: a prisão do condutor é uma espécie de prisão provisória, dispensa a expedição de mandado e o policial deve exigir o recibo de entrega do preso.", { disciplina: "Direito Processual Penal", assunto: "Prisao em flagrante" }),
  certoErrado(110, "A respeito da identificação criminal, do crime de tortura, do abuso de direito, da prevenção do uso indevido de drogas, da comercialização de armas de fogo e dos crimes hediondos: caso três pessoas associadas, com divisão de tarefas, subtraiam substância explosiva, estará configurado crime hediondo.", { disciplina: "Direito Penal", assunto: "Crimes hediondos" }),
  certoErrado(111, "Na mesma tematica (identificação criminal, tortura, abuso de direito, drogas, armas, crimes hediondos): qualquer agente público, ainda que não seja servidor e não perceba remuneração, pode ser sujeito ativo do crime de abuso de autoridade.", { disciplina: "Direito Penal", assunto: "Abuso de autoridade" }),
  certoErrado(112, "Na mesma tematica: mesmo em caso de apresentação do documento de identificação civil, é possível a identificação criminal em caso de constar de registros policiais o uso de outros nomes ou diferentes qualificações.", { disciplina: "Direito Processual Penal", assunto: "Identificacao criminal" }),
  certoErrado(113, "Na mesma tematica: conduzir arma de fogo, no exercício de atividade comercial, sem autorização, configura comércio ilegal de arma de fogo.", { disciplina: "Direito Penal", assunto: "Estatuto do Desarmamento" }),
  certoErrado(114, "Na mesma tematica: entre as atividades de prevenção do uso indevido de drogas, está o fortalecimento da autonomia e da responsabilidade individual em relação ao uso indevido dessas substâncias ilícitas.", { disciplina: "Direito Penal", assunto: "Lei de Drogas" }),
  certoErrado(115, "Na mesma tematica: praticam o crime de tortura policiais rodoviários federais que, dentro de um posto policial, submetem o autor de crime a sofrimento físico, independentemente de sua intensidade.", { disciplina: "Direito Penal", assunto: "Crime de tortura" }),
  certoErrado(116, "À luz da Constituição Federal de 1988 (CF), do Pacto de São José da Costa Rica e do entendimento do Supremo Tribunal Federal, relativos aos direitos humanos: a Convenção Internacional dos Direitos das Pessoas com Deficiência possui status supraconstitucional no ordenamento pátrio, sendo um exemplo de instrumento normativo internacional de caráter inclusivo adotado pelo Brasil para promover a acessibilidade e a autodeterminação de pessoas com deficiência.", { disciplina: "Direitos Humanos", assunto: "Tratados internacionais de direitos humanos" }),
  certoErrado(117, "Ainda sobre direitos humanos: a mera intuição de que esteja havendo tráfico de drogas em uma casa não configura justa causa para autorizar o ingresso sem mandado judicial ou sem o consentimento do morador, exceto em caso de flagrante delito.", { disciplina: "Direitos Humanos", assunto: "Inviolabilidade de domicilio" }),
  certoErrado(118, "Ainda sobre direitos humanos: o aviso prévio é uma condicionante ao exercício do direito de reunião previsto na CF: a inexistência de notificação às autoridades competentes torna ilegal a manifestação coletiva.", { disciplina: "Direitos Humanos", assunto: "Liberdade de reuniao" }),
  certoErrado(119, "Ainda sobre direitos humanos: a Declaração Universal dos Direitos Humanos, um dos primeiros instrumentos normativos gerais de direitos humanos adotados por uma organização internacional, destacou-se pelo fato de comportar a ideia de dignidade da pessoa humana como ponto de convergência da ética universal e do fundamento valorativo do sistema protetivo global dos direitos humanos.", { disciplina: "Direitos Humanos", assunto: "Declaracao Universal dos Direitos Humanos" }),
  certoErrado(120, "Ainda sobre direitos humanos: a alteração do gênero nos assentamentos de registro civil independe da realização de procedimento cirúrgico, denominado transgenitalização, ou da comprovação da realização de tratamentos hormonais ou patologizantes, por parte da pessoa interessada.", { disciplina: "Direitos Humanos", assunto: "Identidade de genero" }),
  {
    numero: 121,
    tipo: "DISSERTATIVA" as const,
    enunciado: `PROVA DISCURSIVA. Considerando que os fragmentos de texto apresentados a seguir têm caráter motivador, redija um texto dissertativo acerca do seguinte tema: A INOVAÇÃO LEGISLATIVA COMO INSTRUMENTO PARA A REDUÇÃO DOS ACIDENTES DE TRANSPORTE TERRESTRE (ATT).

Texto motivador 1: O gráfico anterior mostra a evolução das mortes por acidente de 1996 a 2013, período que inclui a implementação de legislação de trânsito mais rígida, como o novo CTB em 1998 (Lei n.º 9.503/1997) e a nova lei de consumo zero de álcool de 2008, chamada popularmente de Lei Seca (Lei n.º 11.705/2008). (Carlos Henrique Ribeiro de Carvalho. Mortes por acidentes de transporte terrestre no Brasil. Texto para Discussão 2212. IPEA, Brasília, 2016, com adaptações.)

Texto motivador 2: A grande inovação e, talvez, mais importante do Código de Trânsito de 1997 foi a apresentação de um capítulo específico sobre os crimes de trânsito, que não existia no código anterior. As sanções penais relativas às infrações cometidas no trânsito eram apreciadas pelo Código Penal (Decreto-lei n.º 2.848/1940) e pela Lei de Contravenções Penais (Decreto-lei n.º 3.688/1941). (Diego de Freitas Moriyama Silva. Os crimes de trânsito na legislação brasileira. TCC, UFPR, 2018, com adaptações.)

Texto motivador 3: Segundo dados da Polícia Rodoviária Federal (PRF), apenas durante parte da pandemia (11/3/2020 a 31/5/2020), foram contabilizados 11.268 acidentes, sendo 969 deles (8,6%) provocados pela ingestão de álcool. O consumo de álcool foi responsável por 7% do total de óbitos, que chegaram a 958. Ao longo de 2019, o total de acidentes provocados por bebidas alcoólicas foi de 5.631, sendo 1.412 graves. Além disso, cerca de 18 mil motoristas foram notificados por terem sido flagrados dirigindo sob o efeito de álcool. (Internet: www.gov.br, com adaptações.)

Ao elaborar seu texto, aborde os seguintes aspectos:
1 - o impacto da previsão dos crimes de trânsito no que se refere aos ATTs e as possíveis causas desse impacto; [valor: 5,00 pontos]
2 - o impacto da Lei Seca no que se refere aos ATTs e as possíveis causas desse impacto; [valor: 5,00 pontos]
3 - ações para a redução dos ATTs. [valor: 9,00 pontos]`,
    disciplina: "Redacao",
    assunto: "Prova discursiva CEBRASPE",
    dificuldade: "HARD" as const,
    textoApoioChave: undefined,
    comentario: `PADRÃO DE RESPOSTA (grade oficial CEBRASPE) — nao ha gabarito unico, a redacao e avaliada por quesitos:

Quesito 2.1 (impacto da previsao dos crimes de transito, 0 a 3 pontos):
0 - Nao abordou o impacto nem citou causas.
1 - Mencionou o impacto mas nao desenvolveu nem citou causas.
2 - Mencionou impacto e causas, mas de forma inconsistente.
3 - Explicou consistentemente o impacto e citou causas.

Quesito 2.2 (impacto da Lei Seca, 0 a 3 pontos): mesma escala do quesito 2.1, aplicada ao impacto da Lei Seca.

Quesito 2.3 (acoes para reducao dos ATTs, 0 a 3 pontos):
0 - Nao mencionou acoes.
1 - Mencionou acoes mas nao desenvolveu.
2 - Desenvolveu acoes com exemplos, mas de forma inconsistente.
3 - Desenvolveu acoes articuladas com o tema, com exemplos.

Ao dominio do conteudo sao atribuidos ate 20,00 pontos, dos quais ate 1,00 ponto e atribuido a apresentacao e estrutura textual.`,
    alternativas: [] as { letra: string; texto: string; correta: boolean }[],
  },
];
